apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ecommerce
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/orderdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATA_REDIS_HOST: redis-server
  SPRING_DATA_REDIS_PORT: "6379"
  application.yml: |
    spring:
      cloud:
        openfeign:
          client:
            config:
              user-service:
                url: http://user-service
              product-service:
                url: http://product-service
              payment-service:
                url: http://payment-service
              default:
                connectTimeout: 5000
                readTimeout: 5000
    eureka:
      client:
        enabled: false
        register-with-eureka: false
        fetch-registry: false
