apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../services/user-service
  - ../../services/product-service
  - ../../services/order-service
  - ../../services/config-server

namePrefix: prod-

commonLabels:
  environment: production

configMapGenerator:
  - name: global-config
    literals:
      - ENVIRONMENT=production

images:
  - name: IMAGE_NAME
    newTag: v1.0.0

replicas:
  - name: user-deployment
    count: 3
  - name: product-deployment
    count: 3
  - name: order-deployment
    count: 3

