package com.kawashreh.ecommerce.product_service.application.service;

import com.kawashreh.ecommerce.common.exceptions.NoSuchElementException;
import com.kawashreh.ecommerce.product_service.domain.model.Product;
import com.kawashreh.ecommerce.product_service.domain.service.ProductService;
import com.kawashreh.ecommerce.product_service.infastructure.http.client.UserServiceClient;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

/**
 * Regression coverage for GH #41: createProduct used to return null (silently) when the
 * owning user could not be found, which let the controller respond 201 Created with an
 * empty body. It must now throw so a handler can map it to a real 4xx.
 */
@ExtendWith(MockitoExtension.class)
class ProductApplicationServiceTest {

    @Mock
    private UserServiceClient userServiceClient;

    @Mock
    private ProductService productService;

    private ProductApplicationService applicationService;

    @Test
    void createProduct_shouldThrow_whenOwningUserDoesNotExist() {
        applicationService = new ProductApplicationService(userServiceClient, productService);
        UUID ownerId = UUID.randomUUID();
        Product product = Product.builder().ownerId(ownerId).build();

        given(userServiceClient.retrieveUser(ownerId)).willReturn(null);

        assertThatThrownBy(() -> applicationService.createProduct(product))
                .isInstanceOf(NoSuchElementException.class);

        verify(productService, never()).save(org.mockito.ArgumentMatchers.any());
    }

    @Test
    void createProduct_shouldReturnWhatPersistenceActuallySaved_notTheStalePreSaveInput() {
        // Regression: createProduct used to call productService.save(product) and then
        // return the original, pre-save `product` object - which has a null id, since
        // ids are generated by the DB on insert. A caller creating a resource never got
        // back the id they needed for any follow-up call. Must return whatever
        // productService.save() actually persisted instead.
        applicationService = new ProductApplicationService(userServiceClient, productService);
        UUID ownerId = UUID.randomUUID();
        Product product = Product.builder().ownerId(ownerId).build();
        Product persisted = Product.builder().id(UUID.randomUUID()).ownerId(ownerId).build();

        given(userServiceClient.retrieveUser(ownerId))
                .willReturn(com.kawashreh.ecommerce.product_service.infastructure.http.dto.UserDto.builder()
                        .id(ownerId)
                        .build());
        given(productService.save(product)).willReturn(persisted);

        Product result = applicationService.createProduct(product);

        assertThat(result).isEqualTo(persisted);
        assertThat(result.getId()).isNotNull();
        verify(productService).save(product);
    }
}
