server:
  port: 3000

spring:
  application:
    name: frontend-service
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

api:
  gateway:
    base-url: ${API_GATEWAY_BASE_URL:http://localhost:8765}

jwt:
  secret: 5367566859703373367639792F423F452848284D6251655468576D5A71347437
  expiration: 1800000


management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
