apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - overlays/dev
  # Uncomment to apply specific environment:
  # - overlays/staging
  # - overlays/prod

