# ===============================
# Order Service - Local Profile
# For running from IDE without Docker
# ===============================

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: postgres
    password: test1234
  data:
    redis:
      host: redis
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
