apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  v1__create__databases.sql: |
    CREATE DATABASE userdb;
    CREATE DATABASE productdb;
    CREATE DATABASE orderdb;
    CREATE DATABASE paymentdb;
