apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: ecommerce
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/paymentdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATA_REDIS_HOST: redis-server
  SPRING_DATA_REDIS_PORT: "6379"
  application.yml: |
    spring:
      cloud:
        openfeign:
          client:
            config:
              default:
                connectTimeout: 5000
                readTimeout: 5000
    eureka:
      client:
        enabled: false
        register-with-eureka: false
        fetch-registry: false
