apiVersion: v1
kind: Secret
metadata:
  name: SERVICE_NAME-secrets
  namespace: ecommerce
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "DB_USERNAME"
  SPRING_DATASOURCE_PASSWORD: "DB_PASSWORD"

