apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/userdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATA_REDIS_HOST: redis-server
  SPRING_DATA_REDIS_PORT: "6379"
