apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../services/user-service
  - ../../services/product-service
  - ../../services/order-service
  - ../../services/config-server

namePrefix: dev-

commonLabels:
  environment: dev

configMapGenerator:
  - name: global-config
    literals:
      - ENVIRONMENT=development

images:
  - name: IMAGE_NAME
    newTag: dev-latest

